driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-5.11
  - name: centos-6.8
  - name: centos-7.2
  - name: debian-7.11
    run_list: apt::default
  - name: debian-8.5
    run_list: apt::default
  - name: freebsd-9.3
    run_list: freebsd::portsnap
  - name: freebsd-10.3
    run_list: freebsd::portsnap
  - name: fedora-24
    run_list: yum::dnf_yum_compat
  - name: opensuse-13.2
  - name: opensuse-leap-42.1
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default
  - name: macosx-10.10
    run_list: homebrew::default
    driver:
      box: chef/macosx-10.10 # private box in Chef's Atlas account
      provider: vmware_fusion
  - name: macosx-10.11
    run_list: homebrew::default
    driver:
      box: chef/macosx-10.11 # private box in Chef's Atlas account
      provider: vmware_fusion

suites:
  - name: default
    run_list: openssh::default
  - name: iptables
    run_list: openssh::iptables
    excludes:
      - macosx-10.10
      - macosx-10.11
